### PR TITLE
STORY-4754_country_advertiser_campaigns_ui_api: added campaign countr…

### PR DESCRIPTION
**Pull request by Vicentecarrillo**
…y to NI advertiser campaign table and examples

@mikeweaver

### CODE REVIEW

**Comment by mikeweaver** [comment]
Should we also add country to examples for POST and PUT?

**Comment by Vicentecarrillo** [comment]
I added it to POST. I don't think it makes sense to add it to the existing PUT example as it is centered around updating an IVR tree

**Comment by mikeweaver** [comment]
LGTM

**Comment by Vicentecarrillo** [comment]
@mikeweaver can you merge this? I don't have permissions

**Pull request merged**
