### PR TITLE
96/eb/STORY-1513 add documenation for local promo number creation

### PR DESCRIPTION
**Pull request by jebentier**
@mikeweaver @spencerpbartz This is the documentation part of STORY-1513

### CODE REVIEW

**Comment by mikeweaver** [comment]
Something looks fishy with the 03-01-2016 branch, it doesn't contain the version date in the doc_versions.py file. @spencerpbartz Can you take a look?

**Comment by spencerpbartz** [comment]
@mikeweaver You were right. `doc_versions.py` has been updated since Doru created 2016-03-01. Further, branching off of 2016-03-01 caused the outdatedness to cascade. 

To avoid this in the future, should our branching strategy be to always branch off the current live version?

**Comment by mikeweaver** [comment]
Yes, I think that is the proper branching strategy. Please update the docs
to reflect this.

On Mon, Mar 21, 2016 at 7:55 PM, spencerpbartz notifications@github.com
wrote:

> @mikeweaver https://github.com/mikeweaver You were right.
> doc_versions.py has been updated since Doru created 2016-03-01. Further,
> branching off of 2016-03-01 caused the outdatedness to cascade.
> 
> To avoid this in the future, should our branching strategy be to always
> branch off the current live version?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Invoca/developer-docs/pull/30#issuecomment-199603555

## 

http://www.invoca.com/

_Mike Weaver_

Director of Software Engineering

m:| (805) 448-8900 <8054488900>

p: | (805) 880-7711 <8058807711>

skype: | mike.r.weaver

[image: Invoca Named to Inc. 500 List of Fastest-Growing Private Companies]
http://www.invoca.com/about/press/invoca-named-inc-500-list-fastest-growing-private-companies/
Invoca
Named to Inc. 500 List of Fastest-Growing Private Companies
http://www.invoca.com/about/press/invoca-named-inc-500-list-fastest-growing-private-companies/

**Comment by jebentier** [comment]
okay, so what should we do?  should i go ahead and merge this into 2016-03-01 and then we take care of merging and updating those files from master in that branch after?

**Comment by mikeweaver** [comment]
I think you should make sure 2016-02-01 is merged to master, then merge master into 2016-03-01. Once it has been QA'd and is live, merge 2016-03-01 to master.

**Comment by spencerpbartz** [comment]
@mikeweaver Are we still using the "master" branch? I thought we declared that not useful since it has no information about which overall API version it refers to.

**Comment by mikeweaver** [comment]
Ahhh, good point. I had though we still needed master because of the
“latest” release in RTD. But, upon inspection, I see we don’t actually need
it. I suppose we should just delete the master branch then. It will be a
little more maintenance in GitHub as we will need to change the default
branch each time we make a new version, but seems worth it to prevent
confusion.

On Tue, Mar 22, 2016 at 1:59 PM, spencerpbartz notifications@github.com
wrote:

> @mikeweaver https://github.com/mikeweaver Are we still using the
> "master" branch? I thought we declared that not useful since it has no
> information about which overall API version it refers to.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Invoca/developer-docs/pull/30#issuecomment-200022675

## 

http://www.invoca.com/

_Mike Weaver_

Director of Software Engineering

m:| (805) 448-8900 <8054488900>

p: | (805) 880-7711 <8058807711>

skype: | mike.r.weaver

[image: Invoca Named to Inc. 500 List of Fastest-Growing Private Companies]
http://www.invoca.com/about/press/invoca-named-inc-500-list-fastest-growing-private-companies/
Invoca
Named to Inc. 500 List of Fastest-Growing Private Companies
http://www.invoca.com/about/press/invoca-named-inc-500-list-fastest-growing-private-companies/

**Comment by spencerpbartz** [comment]
I assumed that was already what we were doing. 
It's #5 at the beginning of our readme of death.

**Pull request merged**
