### PR TITLE
2016 02 01 story 3745 dev docs vs. new overall API version

### PR DESCRIPTION
**Pull request by spencerpbartz**
Request a simple CR
All, this has already been code reviewed and no life-threatening problems were foreseen.
On the other hand there have been some collisions lately so I thought I'd make everything explicit. 

@mikeweaver 
Man you really had to give that thing a root canal to handle the CSS.  Awesome work on that. As proposed, we're going to continue supporting GET requests for at least 3 operations in the Network Integration API. 

@nburwell I know this isn't exactly the ticket  you agreed to help us on but we could use your expertise. 

@zmathe-sv @codingiam @jebentier @Inanepenguin 
If you fellas are interested, please have a look!
Best,
-SPB

### CODE REVIEW

**Comment by nburwell** [comment]
@spencerpbartz I'm not sure what you'd like me to review or help with here.. since it's already been reviewed and iterated on.  I am very interested in seeing the missing fields from Transactions API in the portal, is that coming soon in another branch?   Please tag me on that one, and please clarify if there's anything specific you want my eyes on for this PR.  Thanks

**Comment by spencerpbartz** [comment]
@nburwell Thanks. Just looking for that official thumbs up for my records!
I will be focusing on the parameter list ticket today

**Comment by nburwell** [comment]
I hope @mikeweaver can give that thumbs up.. I am fairly removed from this ticket. Interested to review the parameter list one though

**Comment by spencerpbartz** [comment]
@mikeweaver Thanks for sorting out that last auto-cherry pick thing with me. 
Merging!

**Pull request merged**
