### PR TITLE
Story 13350 update post delete phone numbers

### PR DESCRIPTION
**Pull request by gabezurita**
STORY-13350 update post/delete phone_numbers endpoint on the sms_messaing service

image
image

## Checklist

- [x] Find the [Service owning team](https://docs.google.com/spreadsheets/d/1YF2wuepY5SZTpVEdT9gwhTPhpnDGZeVjywEwvbJS5TQ/edit#gid=0&fvid=1520238175) for these changes, and tag the team as "Reviewers" on this PR
- [x] Test the documentation changes on readthedocs as a private branch
- [x] If changing general content, have agreement on whether to apply to latest version or all versions (if all versions, provide links to the related PRs below)

### CODE REVIEW

**Comment by caitlinrhd** [comment]
What was changed with the DELETE endpoint? The screenshot looks the same as what's currently live to me.

**Comment by gabezurita** [comment]
> What was changed with the DELETE endpoint? The screenshot looks the same as what's currently live to me.

Ah, my bad — the DELETE endpoint was not changed, only [POST phone_numbers](https://github.com/Invoca/sms-messaging/pull/277/files) — mainly, now `enabled_at` has a date-time value when a phone number is enabled:
image

**Review by caitlinrhd — APPROVED** [review]
Based on screenshots, seems fine to me. 👍

**Review by jbuehring — APPROVED** [review]
👑

**Comment by gabezurita** [comment]
Hi @caitlinrhd, I resolved merge conflicts on this — can we get it merged?

**Comment by omeedrj** [comment]
Merging ([slack discussion](https://invoca.slack.com/archives/C020H726YAX/p1678469010319029))

**Pull request merged**
