### PR TITLE
Correct versions for COAPI and Trans

### PR DESCRIPTION
**Pull request by jakesutton**
Dear @spencerpbartz, I failed to do properly set these versions. 
Please confirm this change is all that's needed?

### CODE REVIEW

**Comment by spencerpbartz** [comment]
@jakesutton Yep that's all you need to do to have that date show up for overall version 2016-02-01. You can check that the dates are changed when you build your version on RTD. (I'll assume QA has made API calls using URLs with those dates to verify they work). 

:+1:

**Comment by jakesutton** [comment]
@spencerpbartz Certainly, @bhberson did QA API updates at the time. Still a fun assumption, though, let's check!

```
> curl -k -H "Content-Type: application/json" -X POST -d '{"transaction_id":"FADD693F-A3F166DB","outcome_name":"DemoNetwork","oauth_token":"VTmb_BefP-liZjICoAc16-KHKCeWqRcZ"}' https://www.invoca.net/api/2016-02-01/call_outcomes.json

{"call_outcome":{"transaction_id":"A1A9CF04-92C75B98","corrects_transaction_id":null,"outcome_name":"DemoNetwork","description":"","occurred_at_time_t":"1458332709","partner_unique_id":"","sale_amount":"","value":"true","custom_parameter_1":"","custom_parameter_2":"","custom_parameter_3":""},"call":{"transaction_id":"FADD693F-A3F166DB","start_time_t":"1453330633"}}
```

Um, I don't have a good `curl` for production TransAPI...

**Comment by spencerpbartz** [comment]
@jakesutton I got confirmation from @gabe-kent that an API call to the TX API works with the date `2016-02-01`

**Comment by jakesutton** [comment]
Rock & roll. @spencerpbartz if I hit the "Merge pull request" button, will RTD live update or do I need to have it rebuild?

**Comment by spencerpbartz** [comment]
@jakesutton Maybe... Your version is still in the "Inactive" list on RTD. I'll slack you.

**Pull request merged**
